# For general information of how to configure prospector visit
# https://prospector.landscape.io/en/master/profiles.html

inherits:
  - strictness_high
ignore-paths:
  - scratch_files
  - cwepr/io/__init__.py
  - cwepr/io/emx_esp.py
  - cwepr/io/general.py

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213

pylint:
  options:
    max-attributes: 12
    max-module-lines: 3000

pyroma:
  run: true

pep8:
  options:
    max-line-length: 80
