# For general information of how to configure prospector visit
# https://prospector.landscape.io/en/master/profiles.html

inherits:
  - strictness_high
ignore-paths:
  - scratch_files
  - cwepr/io/__init__.py
  - build/

pydocstyle:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213

pylint:
  options:
    max-attributes: 12
    max-module-lines: 3000

pycodestyle:
  disable:
    - E203
    - W503
  enable:
    - W504

pyroma:
  run: true

pep8:
  options:
    max-line-length: 80
